server:
  port: 8883

spring:
  application:
    name: vmqtt-cluster

# gRPC配置
grpc:
  server:
    port: 9992
  client:
    peer:
      negotiation-type: plaintext

# Raft集群配置
raft:
  server-id: node1
  group-id: vmqtt-cluster
  data-path: ./data/raft
  snapshot-interval: 3600
  election-timeout: 1000
  heartbeat-interval: 500

# 集群发现配置
cluster:
  discovery:
    enabled: true
    peers:
      - localhost:9992
      - localhost:9993  
      - localhost:9994
  
# 负载均衡配置
load-balancer:
  strategy: consistent-hash
  health-check:
    interval: 10s
    timeout: 5s

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,raft
  endpoint:
    health:
      show-details: always

# 日志配置
logging:
  level:
    com.vmqtt: DEBUG
    root: INFO